//actions
export const LOGINBUYERACTION = "LOGINBUYERACTION";
export const LOGINSELLERACTION = "LOGINSELLERACTION";
export const LOGOUTUSER = "LOGOUTUSER";
export const LOGINUSERFROMLOCALSTORAGE = "LOGINUSERFROMLOCALSTORAGE";
//Mutations
export const LOGINUSERSUCCESS = "LOGINUSERSUCCESS";
export const LOGINUSERFAILED = "LOGINUSERFAILED";
export const LOGOUTUSERSUCCESS = "LOGOUTUSERSUCCESS";
//Getters
export const AUTHGETTER = "AUTHGETTER";
export const USERLOGGEDINGETTER = "USERLOGGEDINGETTER";
export const USERLOGGEDINTYPE = "USERLOGGEDINTYPE";
