//actions
export const LOGINBUYERACTION = "LOGINBUYERACTION";
export const LOGINSELLERACTION = "LOGINSELLERACTION";
export const LOGOUTUSER = "LOGOUTUSER";
export const LOGINUSERFROMLOCALSTORAGE = "LOGINUSERFROMLOCALSTORAGE";
export const SELLERID = "SELLERID";
export const USERPROFILE = "USERPROFILE";

export const LOGINADMINACTION = "LOGINADMINACTION";
export const SIGNUPBUYERACTION = "SIGNUPBUYERACTION";


//Mutations
export const LOGINUSERSUCCESS = "LOGINUSERSUCCESS";
export const LOGINUSERFAILED = "LOGINUSERFAILED";
export const LOGOUTUSERSUCCESS = "LOGOUTUSERSUCCESS";

export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPFAILED = "SIGNUPFAILED";

//Getters
export const AUTHGETTER = "AUTHGETTER";
export const USERLOGGEDINGETTER = "USERLOGGEDINGETTER";
export const USERLOGGEDINTYPE = "USERLOGGEDINTYPE";

//PRODUCTS
//actions
export const CREATE_PRODUCT_ACTION = "CREATE_PRODUCT_ACTION";
//mutations
export const PRODUCTCREATEDSUCCESS = "PRODUCTCREATEDSUCCESS";
export const PRODUCTCREATIONFAILED = "PRODUCTCREATIONFAILED";
//getters
export const PRODUCTCREATED = "PRODUCTCREATED";
export const PRODUCTCREATIONERROR = "PRODUCTCREATIONERROR";

